# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pylint pytest
      - run:
          name: Run pylint
          command: |
            pylint simplevcs
      - run:
          name: Run pytest
          command: |
            pytest tests/
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel
      - run:
          name: Test command-line interface
          command: |
            pip install .
            SimpleVCS init /tmp/repo
            SimpleVCS commit /tmp/repo "Initial commit"
            SimpleVCS log /tmp/repo
      - run:
          name: Deploy to TestPyPI
          command: python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --username __token__ --password $TEST_PYPI_TOKEN
          environment:
            TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
      - run:
          name: Deploy to PyPI
          command: python -m twine upload dist/* --username __token__ --password $PYPI_TOKEN
          environment:
            PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
